version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./media:/media
    restart: always

  proxy:
    container_name: proxy
    image: huecker.io/library/nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/media
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
